export const APP_TITLE = "Movie Catalog";
export const MINS = "Mins";
export const FAILED_LOADING_DATA = "Failed to Fetch Data...";
export const LOADING_DATA = "Loading Data...";
export const CAST = "Cast";
export const SYNOPSIS = "Synopsis";
export const RELEASE_YEAR = "Release Year";
export const DURATIION = "Duration";
export const RATING = "Rating";
